### ISSUE TITLE
React is not needed.

### ISSUE THREAD

**Issue by Mozart409** [SaltyAom/nextjs-preactX#18]
Hello, 

react and react-dom is actually not needed to run nextjs in development or production. See [here](https://github.com/vercel/next.js/tree/canary/examples/using-preact). There is even an official template for it.

If you want I can create an PR with the updates :)

Have a nice day.

**Comment by SaltyAom** [comment]
Thank you for your kind reminder, the reason this repo use webpack alias because at the time this pattern was the only option (around preact 10 alpha) and I forgot about tracking the change for updating this repo.
I also use that pattern on my newer side-project. I'll update to the pattern you suggested, thank you!
